name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore "SW.UserService.sln"
    - name: Build
      run: dotnet build "SW.UserService.sln" --configuration Release --no-restore
    - name: Test
      run: dotnet test "SW.UserService.sln" --no-restore --verbosity normal